# Path to this config can be set via env variable 'CONFIG_FILE'

sunrise:
  start: 07:55
  action:
    - trigger.mist.disable.35m # don't mist for the first 35 mins in the morning
    - switch.small_led.on
    - switch.camera-night-vision-1.off
    - switch.camera-night-vision-2.off
    - switch.camera-night-vision-3.off

day:
  start: "08:00"
  action:
    - switch.small_led.on
    - switch.big_led.on
    - switch.uvb.on

night:
  start: "21:00"
  action:
    - switch.small_led.off
    - switch.big_led.off
    - switch.uvb.off
    - switch.camera-night-vision-1.on
    - switch.camera-night-vision-2.on
    - switch.camera-night-vision-3.on

sunset:
  start: "20:55"
  action:
    - switch.big_led.off
    - alert.temperature.disable.1h # disable temperature alert for 1 hour (allow to settle from day to night temps)

trigger:
  - id: heating
    sensor: temperature
    when:
      day:
        below: 28
      night:
        below: 22
    action:
      - switch.heater.on
    else:
      - switch.heater.off
  - id: fan
    sensor: humidity
    when:
      day:
        above: 84
      night:
        above: 87
    action:
      - switch.fan.on.10m
      - switch.fan.off
      - sleep.10m
    else:
      - switch.fan.off
  - id: preventMist
    endpoint: /prevent-mist
    action:
      - trigger.mist.disable.40m # disable the below trigger for 40m
  - id: doorOpened
    sensor: humidity
    when:
      day:
        droppedBy: 5 # usually when terrarium doors are opened
    action:
      - trigger.mist.disable.30m # disable the below trigger for 30m
  - id: mist
    sensor: humidity
    when:
      day:
        below: 61 # trigger if humidity drops below 61
        every: 4h # trigger every 4h, if not triggered by the above low humidity (just in case they want a drink!)
    action:
      - switch.small_led.off
      - switch.big_led.off
      - switch.uvb.off
      - switch.small_led.disable # disable other wise 'day mode' will turn these back on
      - switch.big_led.disable # disable other wise 'day mode' will turn these back on
      - switch.uvb.disable # disable other wise 'day mode' will turn these back on
      - switch.fan.disable.45m # there's an action that turns on the fan if humidity is high and it's about to be
      - alert.humidity.disable.1h # disable humidity alert for 1 hour
      - echo.Misting will begin in 5m
      - sleep.5m
      - switch.mister.on.7s
      - sleep.2s
      - switch.small_led.enable
      - switch.big_led.enable
      - switch.uvb.enable
      - switch.small_led.on
      - switch.big_led.on
      - switch.uvb.on
      - sleep.1h # do not trigger this for at least another hour
  # - id: test
  #   when:
  #     day:
  #       every: 1m # trigger every 1m
  #   action:
  #     - switch.small_led.off

switch:
  - id: small_led
    on: http://sonoff-lan-api:8080/turnOn/small-led
    off: http://sonoff-lan-api:8080/turnOff/small-led
  - id: big_led
    on: http://meross-lan-api:8080/turnOn/big-led
    off: http://meross-lan-api:8080/turnOff/big-led
    status: http://meross-lan-api:8080/status/big-led
    jsonPath: Status
  - id: uvb
    on: http://sonoff-lan-api:8080/turnOn/uvb
    off: http://sonoff-lan-api:8080/turnOff/uvb
  - id: heater
    on: http://meross-lan-api:8080/turnOn/heat-lamp
    off: http://meross-lan-api:8080/turnOff/heat-lamp
    status: http://meross-lan-api:8080/status/heat-lamp
    jsonPath: Status
  - id: mister
    on: http://meross-lan-api:8080/turnOn/mister
    off: http://meross-lan-api:8080/turnOff/mister
    status: http://meross-lan-api:8080/status/mister
    jsonPath: Status
  - id: fan
    on: http://terrarium-fan-control:8080/turnOn
    off: http://terrarium-fan-control:8080/turnOff
  - id: camera-night-vision-1
    on: https://root:${CAMERA_PASSWORD}@dafang/cgi-bin/action.cgi?cmd=toggle-rtsp-nightvision-on
    off: https://root:${CAMERA_PASSWORD}@dafang/cgi-bin/action.cgi?cmd=toggle-rtsp-nightvision-off
    insecure: true # ignore ssl certificate
  - id: camera-night-vision-2
    on: https://root:${CAMERA_PASSWORD}@dafang/cgi-bin/action.cgi?cmd=ir_led_on
    off: https://root:${CAMERA_PASSWORD}@dafang/cgi-bin/action.cgi?cmd=ir_led_off
    insecure: true # ignore ssl certificate
  - id: camera-night-vision-3
    on: https://root:${CAMERA_PASSWORD}@dafang/cgi-bin/action.cgi?cmd=ir_cut_off
    off: https://root:${CAMERA_PASSWORD}@dafang/cgi-bin/action.cgi?cmd=ir_cut_on
    insecure: true # ignore ssl certificate

sensor:
  - id: temperature
    url: http://terrarium-temp-sensor:8080
    jsonPath: Temperature
    unit: °C
  - id: humidity
    url: http://terrarium-temp-sensor:8080
    jsonPath: Humidity
    unit: "%"

notification:
  - id: pushover
    device: Alec-Phone
    sound: tugboat
    userToken: PUSHOVER_USER_TOKEN # env variable name
    apiToken: PUSHOVER_APP_TOKEN # env variable name
    antiSpam: 1h # only receive alerts once an hour

alert:
  - id: temperature
    sensor: temperature
    when:
      day:
        below: 22
        above: 32
      night:
        below: 17
        above: 26
    after: 30m # only alert after 30 minutes
    notification:
      - pushover
  - id: humidity
    sensor: humidity
    when:
      day:
        below: 57
        above: 89
      night:
        below: 57
        above: 89
    after: 30m # only alert after 30 minutes
    notification:
      - pushover
