name: test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.1
      -
        name: Vet
        run: cd cmd/terrarium-bot-v2 && go vet
      -
        name: Build
        run: cd cmd/terrarium-bot-v2 && go build -v
      -
        name: Test
        run: cd cmd/terrarium-bot-v2 && go test -v
